### Q1. Use numpy to generate array of 25 random numbers sampled from a standard normal distribution

In Numpy, we are provided with the module called random module that allows us to work with random numbers. The random module provides different methods for data distribution.<br>
In this question, I have created an array of 25 random numbers that are part of a normal distribution or Gaussian distribution. This distribution is also called the Bell Curve this is because of its characteristics shape.<br><br>
**Syntax:** numpy.random.normal(loc = 0.0, scale = 1.0, size = None)<br>

**Parameters:**<br>

**loc:** Mean of distribution<br>
**scale:** Standard derivation<br> 
**size:** Resultant shape<br>

In [1]:
import numpy as np

numbers = np.random.normal(size = 15)

print(numbers)

[ 0.36263918 -0.96784972 -0.30442832 -0.88501074  1.69424311 -1.11152024
  0.91440971  0.23788042  0.57860273 -0.69167636  0.1539945   0.99989031
 -0.45316963  0.36564427 -0.72134379]


### Q2. Create a random vector of size 30 and find the mean value.

In [2]:
import numpy as np

arr = np.random.randint(low = 0, high = 30, size = 30)

print(arr)

arr.mean()

[22 28 12 15 21 19 21 11  3 20 21  8 21 29  0 23 29  0 22  9 24 18 26 24
  2 15 14 16 13  7]


16.433333333333334

### Q3. Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.

In [7]:
import numpy as np

num = np.arange(1,101)

print(f"array before reshape:\n {num}")

num = np.reshape(num,(10,10))

print(f"\narray after reshape:\n {num}")

array before reshape:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

array after reshape:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


### Q4. Create a 10x10 array with random values and find the minimum and maximum values.

In [8]:
import numpy as np

values = np.random.random((10,10))

print(f"Minimum value of array: {values.min()}\n")

print(f"Maximum value of array: {values.max()}\n")

Minimum value of array: 0.0011326733424431579

Maximum value of array: 0.9938811924726205



### Q5. Find Dot product of two arrays

### f = np.array([1,2])

### g = np.array([4,5])



In [9]:
import numpy as np

f = np.array([1,2])

g = np.array([4,5])

mul = np.dot(f,g)

print(mul)

14


### Q6. Concatenate following arrays along axis=0

### x=np.array([[1,2],[3,4]])

### y=np.array([[5,6]])

In [10]:
import numpy as np

x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])

comb = np.concatenate((x,y), axis = 0)

print(comb)

[[1 2]
 [3 4]
 [5 6]]


### Q7. How to get the common items between two python numpy arrays?

### a = np.array([1,2,3,2,3,4,3,4,5,6])

### b = np.array([7,2,10,2,7,4,9,4,9,8])

In [11]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

common = np.intersect1d(a,b)

print(common)

[2 4]


### Q8. Sort the numpy array:

### arr = np.array([10,5,8,4,7,2,3,1])

In [12]:
import numpy as np

arr2 = np.array([10,5,8,4,7,2,3,1])

arr2 = np.sort(arr2)

print(arr2)

[ 1  2  3  4  5  7  8 10]
